### ISSUE TITLE
"couldn't find tree entry for path" error

### ISSUE THREAD

**Issue by nocnokneo** [tummychow/git-absorb#1]
Out of the box I was getting a "couldn't find tree entry for path" error, but using the [fork from da-x]( https://github.com/da-x/git-absorb) things worked. Merge those changes?

**Comment by tummychow** [comment]
Heh, so it was completely broken for any files that weren't under the root tree. Thanks for the heads up @nocnokneo , I had seen this error a few times in personal usage but was too lazy to investigate. I'll see about getting @da-x 's fork merged in.

**Comment by tummychow** [comment]
https://crates.io/crates/git-absorb/0.3.0

https://github.com/tummychow/git-absorb/releases/tag/0.3.0

thanks again for flagging the problem
