### ISSUE TITLE
Distribute a binary

### ISSUE THREAD

**Issue by cjlarose** [tummychow/git-absorb#11]
I'd love to recommend this project to my friends and coworkers, but they don't typically have the rust build tools installed.

It'd be awesome if this tool was distributed on homebrew.

**Comment by tummychow** [comment]
conveniently, it is on homebrew now (#10)

i'll upload a linux release binary for 0.3.0 as well, but since it's built on my computer, i have no idea if it runs elsewhere

**Comment by cjlarose** [comment]
Thanks so much!

**Comment by odinho** [comment]
Linux works, very helpful! : )
