### ISSUE TITLE
Please bump `libgit2` to v1.8.0

### ISSUE THREAD

**Issue by lishaduck** [tummychow/git-absorb#114]
Hello! I use `feature.manyFiles`, introduced in Git 2.40. This breaks `libgit2` and, by extension, all applications which statically link it. `libgit2` v1.8.0 adds support for `feature.manyFiles`, and `git2` v0.19.0 uses `libgit2` v1.8.0, but `git-absorb` is still on v0.18.0 of `git2`. Would it be possible to bump?
If it's nontrivial (i.e., more than just a `cargo bump`) and something you're willing to merge, I'd be willing to figure it out, as this looks pretty cool and I'd like to try it 😁

**Comment by tummychow** [comment]
https://github.com/tummychow/git-absorb/releases/tag/0.6.15

**Comment by lishaduck** [comment]
> https://github.com/tummychow/git-absorb/releases/tag/0.6.15

Thanks!

**Comment by lishaduck** [comment]
Oh, I just wanted to let you know that in last week or since since brew upgraded libgit2, I've been very pleased with this! It's amazing just how much easier my life has gotten (and `--fixup` in the meantime was still so much nicer than interactive rebases). Thanks for your hard work!
