### ISSUE TITLE
Elevator pitch code in the readme doesn't work

### ISSUE THREAD

**Issue by gigatexal** [tummychow/git-absorb#121]
Firstly, thank you for this free tool. It has sent me into a git fixup, git rebase rabbit hole and has expanded my knowledge of a git a bit more.

I was also won over by the first part of the elevator pitch:

https://github.com/tummychow/git-absorb?tab=readme-ov-file#elevator-pitch

```
git add $FILES_YOU_FIXED
git absorb --and-rebase
```

I created a silly git repo, added a text file, committed it, then in another edit added another line, ran git absorb --and-rebase and it all worked as expected. There were no fixup! commits in the log.

BUT

```
git add $FILES_YOU_FIXED
git absorb
git log # check the auto-generated fixup commits
git rebase -i --autosquash master
```
Doing the above left the file in the right state of course but left the fixup! init commit in the log :-/ where I expected them to be equivalent i.e the fixup! init commit to be squashed.

I might be doing something wrong here so apologies if this is user error.

Running on git v 2.46.2 on M3 MacBook Pro on MacOS 15

**Comment by tummychow** [comment]
i'm going to need more than that to reproduce the issue. what was the exact state of the repo in each case?

**Comment by gigatexal** [comment]
Sorry bout that, here's the steps I took to recreate:

## setup:

```
cd /tmp
git init
echo "hello world" > foo.txt
git add foo.txt
git commit -m "init"
```

## working 
i.e git log shows one commit with the file having all the fixes because the fixup commit was squashed.

Using the above setup code:

```
echo "PR changes" >> foo.txt
git absorb --and-rebase
# pops up a text editor for me to confirm
# confirmed
git log
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) git log
commit 1f9ad68953a212e087877e562e46307b80240ab7 (HEAD -> main)
Author: gigatexal <alex@alexandarnarayan.com>
Date:   Fri Sep 27 16:08:22 2024 +0200

    init

➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) cat foo.txt
hello world
pr changes
```

## not working
two commits in the git log

```
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) echo "add pr changes using and us
ing absorb with more steps" >> foo.txt
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) ✗ git add foo.txt
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) ✗ git absorb
Sep 27 14:12:01.864 INFO committed, header: +1,-0, commit: 270f3bb30438d655713753a3bd3e352616f97155
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) git log
commit 270f3bb30438d655713753a3bd3e352616f97155 (HEAD -> main)
Author: gigatexal <alex@alexandarnarayan.com>
Date:   Fri Sep 27 16:12:01 2024 +0200

    fixup! init

➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) git rebase -i --autosquash main
commit 1f9ad68953a212e087877e562e46307b80240ab7
Author: gigatexal <alex@alexandarnarayan.com>
Date:   Fri Sep 27 16:08:22 2024 +0200

    init

noop

# Rebase 270f3bb..270f3bb onto 270f3bb (1 command)
#
# Commands:

Successfully rebased and updated refs/heads/main.
```
of course here since it didn't find the the init commit the rebase was a nothing change and the fixup! init commit remains

`git log`

```
➜  ff4d36d09e2c1c2ccf70486c71ff8d72 git:(main) git log
commit 270f3bb30438d655713753a3bd3e352616f97155 (HEAD -> main)
Author: gigatexal <alex@alexandarnarayan.com>
Date:   Fri Sep 27 16:12:01 2024 +0200

    fixup! init

commit 1f9ad68953a212e087877e562e46307b80240ab7
Author: gigatexal <alex@alexandarnarayan.com>
Date:   Fri Sep 27 16:08:22 2024 +0200

    init
```

I hope that helps.

**Comment by tummychow** [comment]
i think you're having a fundamental misunderstanding here. if you manually run rebase, _you have to pick the base of the rebase yourself_. if you just make a test repo with one branch, rebasing the branch you're currently on, onto itself, is a noop. this has nothing to do with git absorb. in your example, if you run git rebase --root instead of git rebase main, you'll see the rebase log as expected. the typical workflow would be that you were running absorb on a _branch of main_, in which case the rebase operation would obviously not be a noop

**Comment by gigatexal** [comment]
Ahh apologies then, thank you!
