### ISSUE TITLE
Sign commit after absorb

### ISSUE THREAD

**Issue by lcheylus** [tummychow/git-absorb#122]
Thanks for your great tool, I just discovered it. Very useful for my Git workflows with fixes + rebase/fixup :+1: 

Usually, I sign all my commits on GitHub (with a dedicated SSH key) via `git -s -S commit`.

When using the "Fixup workflow" (first commit with signature => fix => 2nd commit => rebase/fixup => commit to squash the 2 commits) as abstracted by "absorb", the signature is lost after rebase. I re-sign my commits after rebase via ` git rebase --exec "git commit --amend --no-edit -n -S -s" -i <commit_hash>`.

Could you add an option for `git-absorb` to do the same thing? => `-s` = sign commit after absorb.

**Comment by tummychow** [comment]
git rebase has a flag to sign commits - `-S`, as usual. for my stance on supporting these arguments in git-absorb, see #88. if you want custom flags for your git rebase, my advice would be to invoke rebase yourself, which absorb has always been designed to support

**Comment by lcheylus** [comment]
TIL rebase can sign commits with `-S` flag !

Thanks for your explanations.
