### ISSUE TITLE
Add ability to apply git-absorb to an existing commit.

### ISSUE THREAD

**Issue by clenchedteeth** [tummychow/git-absorb#127]
It sometimes happens that I want to apply git-absorb to an existing commit (either the most recent commit or one further back in the history). It would be nice to be able to do this in some automated way, rather than having to edit a commit via interactive rebase, reset a commit, do a git-absorb on the changes from the commit, and then continuing the rebase. The message for a commit could be modified with a special tag to indicate that the commit should be absorbed. (Perhaps there is a way to achieve this already but I don't see it.)

**Comment by tummychow** [comment]
sorry, but i'm going to decline this one. i explained my rationale here https://github.com/tummychow/git-absorb/issues/44#issuecomment-849977742 i think there's too much complexity to justify a fairly narrow use case

**Comment by clenchedteeth** [comment]
Ok fair enough, thanks for the link (I did try to search first, sorry).
