### ISSUE TITLE
Add an option to use the commit description instead of the hash

### ISSUE THREAD

**Issue by jamesderlin** [tummychow/git-absorb#13]
When I use `git absorb`, it creates fixup commits with commit messages like:

    fixup! ef7cd00ea6a0bb403bc5ac97f31b3b4146eec795

This is not meaningful to me, and it's hard for me to tell if this will update the commit I expect without doing extra work.  It would be nice if `git absorb` (whether by default or via an option) created fixup commits that used the subject of the original commit instead (if there is no ambiguity), as `git commit --fixup` does.

**Comment by tummychow** [comment]
pretty sure this was implemented in #5 ? i haven't cut a release with that yet, but you should get the behavior you want if you use master

**Comment by jamesderlin** [comment]
Ah, I searched for closed issues but failed to search closed PRs. =) Thanks!
