### ISSUE TITLE
Fails if base is annotated tag

### ISSUE THREAD

**Issue by CervEdin** [tummychow/git-absorb#132]
running

```sh
git absorb --base=annotated-tag --fix
```

is giving me

```
Nov 15 17:01:34.073 CRIT absorb failed, err: the requested type does not match the type in the ODB; class=Invalid (3); code=NotFound (-3)
```

**Comment by tummychow** [comment]
hm... that's unfortunate. probably we have to peel_to_commit instead of find_commit, since the revparse result could be any git object type

**Comment by CervEdin** [comment]
Thanks for the quick response!

Guessing you're referring to something related to libgit? Not familiar with that.
Annotated commit are peculiar refs, since they have a hash which is different from the underlying ref which they refer to and I would guess that's the underlying cause for whatever is happening here

In general, I would expect to be able to use any valid refspec as `--base`.

**Comment by tummychow** [comment]
https://github.com/tummychow/git-absorb/pull/135
