### ISSUE TITLE
test_stack_stops_at_default_limit() breaks if ~/.gitconfig sets absorb.maxStack

### ISSUE THREAD

**Issue by nickolay** [tummychow/git-absorb#16]
I had absorb.maxStack set in my `~/.gitconfig` per https://github.com/tummychow/git-absorb#stack-size

This led to `cargo test` failing on test_stack_stops_at_default_limit(), because the test relies on the fact that the default limit is not modified in the global git config.

There doesn't seem to be an easy way to mock it: libgit2 uses [cl_fixture_sandbox](https://github.com/libgit2/libgit2/blob/f92d495d44bff2bdb6fd99524a93986ea268c9e8/tests/repo/config.c#L10) for such tests, which relies on [git_libgit2_opts](https://github.com/libgit2/libgit2/blob/635693d3bc55770ec7a6640ba3f2f0ee434a6042/tests/clar_libgit2.c#L583) to override the path to the global config, and [git2-rs doesn't seem to expose it](https://github.com/rust-lang/git2-rs/search?utf8=%E2%9C%93&q=git_libgit2_opts&type=).

What's the best way to deal with this? I'd remove the test altogether or at least add a comment to it, so that the reason for the failure is clear to future contributors without debugging.

**Comment by tummychow** [comment]
oh... yuck. yeah i'll just delete the test for now
