### ISSUE TITLE
Should git-absorb run git rebase --interactive automatically?

### ISSUE THREAD

**Issue by nickolay** [tummychow/git-absorb#18]
It would be nice if git-absorb ran `git rebase --interactive --autosquash ${BASE}` if it was successful in creating all the fixup commits. This would save typing `git rebase --interactive` and copy-pasting the BASE sha.

Perhaps with a command line flag like `git absorb --and-rebase`, or maybe even `git absorb --and-rebase-with-no-prompt` for the adventurous types. What do you think?

**Comment by tummychow** [comment]
yep, this is in my TODOs. would definitely accept a PR for this

**Comment by nickolay** [comment]
Ah, sorry didn't see the TODO. Submitted the PR; I've elected not to add `--and-rebase-with-no-prompt` though.
