### ISSUE TITLE
No manpage associated to git-absorb

### ISSUE THREAD

**Issue by Joacchim** [tummychow/git-absorb#2]
Hello,

I've found your project recently (after reading a post about hg's absorb actually), and this magnificent mercurial feature really deserved porting to git, so kudos for that o/

Now, I'm trying to use it, and as usual, tend to rely on the help text/pages from the various git modules whenever I'm looking for an option or how to use it, rather than the README of the given project.
As such, I feel like a manpage or detailed helptext is lacking for git-absorb. Is it something that you planned for ?

**Comment by tummychow** [comment]
yeah, it should probably have a manpage, i'm just too lazy to write one. PRs welcome otherwise i'll see about doing this on the weekend

**Comment by giodamelio** [comment]
Just going to mention rust-lang/cargo#2729 here. It's not a thing yet (and may never be), but it might solve the problem of manpage installation eventually.
