### ISSUE TITLE
GitHub release name changed from "git-absorb-linux-x86_64" to "git-absorb" 

### ISSUE THREAD

**Issue by nifr** [tummychow/git-absorb#27]
Hi @tummychow ,
first of all THANKS for your awesome work on `git-absorb`. I myself and our team really appreciate your tool.

Actually we did even include it in our provisioning process for development machines/containers. The recent release sadly broke our builds due to the name change of the release file.

Could you please upload a linux binary named `git-absorb-linux-x86_64` to the `0.6.0` release.
That'd be super awesome. 

Otherwise we'd have to implement some ugly workaround on our side.
Thanks again for the great open-source project and lovely tool !!

Greetings from Germany - have a nice weekend :)

**Comment by tummychow** [comment]
oh lol, yes i wasn't paying enough attention when i uploaded the binary. one sec

**Comment by tummychow** [comment]
should be the same as past releases now
