### ISSUE TITLE
foreign author found

### ISSUE THREAD

**Issue by jtojnar** [tummychow/git-absorb#3]
When I try git-absorb it fails with the following error

    Nov 19 17:53:54.116 WARN foreign author found, commit: bd8171213c322bc49a0e9171abc338ec322b5c45, line: 65, module: git_absorb::stack

**Comment by NiklasMM** [comment]
I would love to see the force flag implemented. I need to be able to fixup other peoples commits.

**Comment by alyssais** [comment]
Should the error message be changed? "WARN foreign author found" doesn't sound particularly friendly, and made me do a double take before I realised what it was saying.
