### ISSUE TITLE
Error handling update: thiserror or anyhow

### ISSUE THREAD

**Issue by alexmaco** [tummychow/git-absorb#31]
Since `failure` is effectively deprecated and unmaintained, I'd like to update the error handling lib.

@tummychow which would you prefer between these 2 ? Anyhow seems more oriented to binaries, so that's what I would go for. Thiserror seems more suited to libraries, however the library form of git-absorb only has one function, so not sure how much value does detailed error insppection brings.

**Comment by tummychow** [comment]
i'm amenable to an anyhow port. just swapping it in for `failure::Error` is fine with me, no need for custom error types
