### ISSUE TITLE
Publish Windows (x64) binaries

### ISSUE THREAD

**Issue by sschuberth** [tummychow/git-absorb#38]
Can we please also get Windows (at least x64) binaries for releases, so Git for Windows users can easily try out this project without the need to install Rust?

**Comment by tummychow** [comment]
i have no windows machines on which to compile those binaries, and i'm not interested in learning to cross compile for a platform i never touch. so the only way it's going to happen is if someone figures out how to do it in ci and sends a pr for that. preferably github actions

**Comment by sschuberth** [comment]
I did some quick searching and https://github.com/Douile/rust-build.action looks like a candidate.
