### ISSUE TITLE
Link to `hg absorb` in README no longer works

### ISSUE THREAD

**Issue by aayjaychan** [tummychow/git-absorb#57]
The link to Facebook's [hg-experimental](https://bitbucket.org/facebook/hg-experimental) repository is no longer valid.

The `absorb` extension has been upstreamed to [core Mercurial](https://www.mercurial-scm.org/repo/hg/file/tip/hgext/absorb.py), so maybe that can be used instead.

**Comment by tummychow** [comment]
ah, thank you for pointing that out. i updated the link to point to the commit where the extension got upstreamed
