### ISSUE TITLE
Create a mac release artifact

### ISSUE THREAD

**Issue by jankatins** [tummychow/git-absorb#59]
I install git-absorb via zinit directly from github and but unfortunately, there is no mac binary available, so it only works on my linux machines :-(

**Comment by jankatins** [comment]
Would you take a PR which adds automatic github release creations from tags (pushing a git tag generates github release + publishes some artifacts into the release via a github action workflow)? If you want, I could adjust e.g. the ripgrep one: https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

**Comment by tummychow** [comment]
yeah sure, i'd accept that pr

**Comment by jankatins** [comment]
Then I will have some fun with github action workflows tomorrow :-)

**Comment by jankatins** [comment]
Took a bit longer, but there is #60 now :-)
