### ISSUE TITLE
[Ubuntu] - unable to locate package git-absorb

### ISSUE THREAD

**Issue by TomasSlama** [tummychow/git-absorb#68]
Hey 👋,

I was trying to follow the docs to install this package.

1. I was trying to get the latest artefact for ubuntu, but it is expired
2. I tried to run `sudo apt install git-absorb` but it ends with error `unable to locate package git-absorb`

![image](https://user-images.githubusercontent.com/6830426/202202426-9e20821a-1e9e-4f2b-ba35-3e80359808c4.png)

**Comment by tummychow** [comment]
i'm not responsible for the packaging of git-absorb on official distribution repositories, but a quick glance shows that it's only available on jammy https://packages.ubuntu.com/search?keywords=git-absorb&searchon=names&suite=jammy&section=all and you're on focal. use the tagged release https://github.com/tummychow/git-absorb/releases/tag/0.6.7
