### ISSUE TITLE
Error: ambiguous lookup

### ISSUE THREAD

**Issue by michal-michalak** [tummychow/git-absorb#73]
Hey,

Do you have any idea what I'm doing wrong? 🤔 This error message doesn't help me a lot. I see that on a few of my repos. 

```zsh
❯ git absorb --base 30 -v
Dec 31 13:04:35.409 CRIT absorb failed, err: ambiguous lookup - OID prefix is too short; class=Object (11); code=Ambiguous (-5), line: 109, module: git_absorb
```

**Comment by tummychow** [comment]
base is not a number, it's a commit. you're saying "i want to use the commit whose id is `30` as the base" and git is saying "well this repo has a lot of commits whose sha1 starts with `30`, that object id is ambiguous". the full range of [gitrevision syntax](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltrevgtltngtemegemHEADmaster3em) is supported; if you want to take the 30th ancestor of HEAD then you can use `--base HEAD~30`.

**Comment by michal-michalak** [comment]
@tummychow 
Damn. It's so obvious. I probably didn't read the documentation carefully enough.. or assumed it's the same type of param as for `maxStack` (which is int). Thank you! And Happy New Year!

**Comment by SuperSandro2000** [comment]
I've just run into this, too. Maybe some validation around the arg or some info in the error could be added?

**Comment by tummychow** [comment]
you can't validate the argument - any valid positive integer is also a valid sha1sum. i would accept a pr that matched the error code (https://docs.rs/git2/latest/git2/enum.ErrorCode.html#variant.Ambiguous) for this specific codepath and returned a custom error that hinted at the issue
