### ISSUE TITLE
high-level description of algorithm 

### ISSUE THREAD

**Issue by aspiers** [tummychow/git-absorb#8]
It would be nice if the algorithm was documented at a high-level, not just so that people can more easily contribute to the code, but also so that users can be aware of any particular strengths or caveats.  For example it seems that it doesn't use libgit2's `blame` APIs - is that right?  In which case, does it just iterate through the `N` most recent commits (where `N` seems to default to 10) looking for commits which change the same lines altered by the fixup hunks?

**Comment by tummychow** [comment]
the best description atm is probably here https://github.com/tummychow/git-scripts/blob/master/git-absorb.md#interlude-patch-theory

but i acknowledge that there should probably be something in this specific repo, and it should probably be refreshed a bit (eg my old implementation of hunk commutation was completely wrong)

**Comment by aspiers** [comment]
Oh cool thanks!  Yes, that file definitely belongs in this repository.  So you are going more down the darcs route than the `blame` route - interesting (I used to use darcs a long time ago, and enjoyed this feature).  I went the opposite way and chose the latter:

- https://github.com/aspiers/git-deps/blob/master/bin/git-fixup
- https://github.com/aspiers/git-deps/blob/master/USE-CASES.md#use-case-4-automatic-squashing-of-fixup-commits

but it has been on my mind for a long time to look deeper into patch theory:

- https://github.com/aspiers/git-deps/issues/39 (hi @waldyrious, I see you are following this issue too ;-)

It would be cool to get your thoughts on this.  I expect there are pros and cons of both approaches.  I expect that pairwise testing of commutativity is probably more efficient than the `blame` algorithm which presumably tries to excavate a lot more information than a simple boolean result, and as a consequence is probably much more expensive.  But I'd have to research git's `blame` algorithm to be sure.

**Comment by gasche** [comment]
I also thought that it would help to describe how the tool work, so that users can form a mental model and not be surprised when using it. It went to read this issue and the long explanation at https://github.com/tummychow/git-scripts/blob/master/git-absorb.md#interlude-patch-theory, and proposed a short summary in the README at #41.
