### ISSUE TITLE
Consider publishing windows binaries to winget/chocolatey package managers

### ISSUE THREAD

**Issue by moswald** [tummychow/git-absorb#85]
[WinGet](https://learn.microsoft.com/en-us/windows/package-manager/package/)

[Chocolatey](https://docs.chocolatey.org/en-us/create/create-packages-quick-start#:~:text=In%20your%20package%20directory%2C%20use%3A%20choco%20install%20package-name,Chocolatey%20account.%20choco%20apikey%20--api-key%20%5BAPI_KEY_HERE%5D%20-source%20https%3A%2F%2Fpush.chocolatey.org%2F)

**Comment by nzbart** [comment]
I just seamlessly installed git-absorb on Debian using `apt`, and wanted to have the same experience on Windows, but couldn't find it on either of the two common package managers above. Supporting either one would be great.

**Comment by tummychow** [comment]
as a general statement for the record, i can't personally be bothered to submit packages to upstream repositories, sorry. i'll leave this open in case someone does submit it (as people have done for a variety of other package managers).

**Comment by nzbart** [comment]
@tummychow Fair enough, and thanks for making this tool! I don't use Windows at home, so won't be able to make an installer package for Windows.

**Comment by drdamour** [comment]
came here to say this, hope it gets done...too many of us are stuck on enterprise windows

 :(

**Comment by moswald** [comment]
I think we could probably get the [winget-pkgs repo](https://github.com/microsoft/winget-pkgs/issues/new/choose) to build one, but the windows releases would need to be .zip instead of .tar.gz. I think double-checking that the [regex on line 137 of `release.yml`](https://github.com/tummychow/git-absorb/blob/master/.github/workflows/release.yml) is doing what's expected is all that's needed.

@tummychow

**Comment by tummychow** [comment]
future releases will have zips instead of tarballs (https://github.com/tummychow/git-absorb/pull/84). i manually added zips to https://github.com/tummychow/git-absorb/releases/tag/0.6.10 as a one-off.

**Comment by moswald** [comment]
[The WinGet packages team is taking care of it](https://github.com/microsoft/winget-pkgs/issues/103855).
