### ISSUE TITLE
Homebrew reports "git-absorb has been deprecated!"

### ISSUE THREAD

**Issue by jthemphill** [tummychow/git-absorb#95]
I see a deprecation warning in Homebrew, but I'm confused as to what I should use instead. Is git-absorb in maintenance mode? Is the homebrew package out of date?

See on Homebrew's website: https://formulae.brew.sh/formula/git-absorb

Or when installing:

```
% brew install git-absorb
Warning: git-absorb has been deprecated!
```

But homebrew is still the recommended way to install `git-absorb`, according to the README:

https://github.com/tummychow/git-absorb/blob/d84f5604eb67967a573a671d34914b10ed56a298/README.md?plain=1#L40

**Comment by jthemphill** [comment]
Thank you for all your work on this!

**Comment by tummychow** [comment]
https://github.com/tummychow/git-absorb/releases/tag/0.6.11 depends on libgit2 1.7.1 which is the latest upstream release. i'm sure someone on the homebrew side will update the package at some point
