### ISSUE TITLE
Thank you for `git-absorb`!

### ISSUE THREAD

**Issue by ErichDonGubler** [tummychow/git-absorb#96]
I'm gonna shake up your issues a bit, and just file this issue to say thanks. Open source is a thankless endeavor, most of the time, and we open source maintainers often have to read between the lines to see how we're making a difference.

Well, I'd like you (and other contributors) to know that `git-absorb` is a huge time-saver for me, in many cases making my work actually possible when I'm making edits in bulk for data I manage in Git repositories. I currently work at Mozilla, but I've used `git-absorb` for multiple years even before then. Thank you for this delightful piece of tooling that lets me focus on ~~turning food into code~~ finding joy in higher-level tasks. 😊

**Comment by ErichDonGubler** [comment]
Feel free to close at any time; I don't want another issue in your count to stress you out!

**Comment by tummychow** [comment]
you're welcome, it's my pleasure. i mostly merge other people's contributions at this point, but i'm always glad to hear that this is a useful tool
